# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/MakeNowJust/heredoc"

[[constraint]]
  branch = "master"
  name = "github.com/bcicen/go-haproxy"

[[constraint]]
  branch = "master"
  name = "github.com/cockroachdb/cmux"

[[constraint]]
  branch = "master"
  name = "github.com/gocarina/gocsv"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  branch = "master"
  name = "github.com/openshift/api"

[[constraint]]
  branch = "master"
  name = "github.com/openshift/client-go"

[[constraint]]
  branch = "master"
  name = "github.com/openshift/library-go"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.1"

[[override]]
  name = "github.com/golang/glog"
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"

[prune]
  go-tests = true
  unused-packages = true
